PER_DEVICE_TRAIN_BATCH_SIZE = 16
GRADIENT_ACCUMULATION_STEPS = 1
LEARNING_RATE = 1e-5
WARMUP_STEPS = 5
GRADIENT_CHECKPOINTING = True
FP16 = True
SAVE_TOTAL_LIMIT = 1
PER_DEVICE_EVAL_BATCH_SIZE = 16
PREDICT_WITH_GENERATE = True
GENERATION_MAX_LENGTH = 225
LOGGING_STEPS = 5
LOAD_BEST_MODEL_AT_END = True
METRIC_FOR_BEST_MODEL = 'wer'
GREATER_IS_BETTER = False
OPTIM = "adamw_bnb_8bit"

# used when training strategy is epoch
NUM_TRAIN_EPOCHS = 1

# used when training strategy is steps
EVAL_STEPS = 10
SAVE_STEPS = 10
MAX_STEPS = 100

